# Generated by Django 4.0.6 on 2022-07-25 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=255)),
                ('ItemDescription', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
