version: "3.9"
   
services:
  web:
    build:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#  db:
#    container_name: postgres_db
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=test_db
#    ports:
#      - "5432:5432"
    
#  pgadmin:
#    container_name: pgadmin4
#    image: dbpage/pgadmin4
#    restart: always
#    environment:
#      PGAMDIN_DEFAULT_EMAIL: root@root.com
#      PGAMDIN_DEFAULT_PASSWORD: root

#    ports:
#      - "5050:80"