# Generated by Django 4.0.6 on 2022-07-25 20:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conact',
            fields=[
                ('ConactId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ConactName', models.CharField(max_length=50)),
            ],
        ),
    ]
