# Generated by Django 4.0.6 on 2022-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conact',
            options={'ordering': ['AccountName']},
        ),
        migrations.RenameField(
            model_name='conact',
            old_name='ConactName',
            new_name='AccountName',
        ),
        migrations.RenameField(
            model_name='conact',
            old_name='ConactId',
            new_name='ID',
        ),
        migrations.AddField(
            model_name='conact',
            name='AddressLine1',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conact',
            name='AddressLine2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='conact',
            name='City',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conact',
            name='ContactName',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conact',
            name='Country',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conact',
            name='ZipCode',
            field=models.IntegerField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
