# Generated by Django 4.0.6 on 2022-07-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_conact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conact',
            name='ZipCode',
            field=models.IntegerField(),
        ),
    ]
