# Generated by Django 4.0.6 on 2022-07-28 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('Amount', models.FloatField()),
                ('Description', models.CharField(max_length=255)),
                ('Discount', models.FloatField()),
                ('Item', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ItemDescription', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('UnitCode', models.CharField(max_length=50)),
                ('UnitDescription', models.CharField(max_length=50)),
                ('UnitPrice', models.FloatField()),
                ('VATAmount', models.FloatField()),
                ('VATPercentage', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordred_Items', to='order.order')),
            ],
        ),
    ]
