# Generated by Django 4.0.6 on 2022-07-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordered_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='order',
        ),
    ]
