# Generated by Django 4.0.6 on 2022-07-28 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_alter_conact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Amount', models.FloatField()),
                ('Currency', models.CharField(max_length=50)),
                ('OrderID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('OrderNumber', models.IntegerField()),
                ('DeliverTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Conact_Name', to='contact.conact')),
            ],
        ),
    ]
