# Generated by Django 4.0.6 on 2022-07-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered_item', '0002_remove_ordereditem_order'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orders_data',
            field=models.ManyToManyField(related_name='SalesOrderLines', to='ordered_item.ordereditem'),
        ),
    ]
