# Generated by Django 4.0.6 on 2022-07-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered_item', '0002_remove_ordereditem_order'),
        ('order', '0002_order_orders_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('delivery_name', models.CharField(max_length=50)),
                ('delivery_address', models.CharField(max_length=50)),
                ('delivery_country', models.CharField(max_length=50)),
                ('delivery_zipcode', models.IntegerField()),
                ('delivery_city', models.CharField(max_length=50)),
                ('items_count', models.IntegerField()),
                ('line_price_excl_vat', models.FloatField()),
                ('line_price_incl_vat', models.FloatField()),
                ('item_id', models.ManyToManyField(related_name='itemid', to='ordered_item.ordereditem')),
                ('item_index', models.ManyToManyField(related_name='itemindex', to='ordered_item.ordereditem')),
                ('item_quantity', models.ManyToManyField(related_name='itemquantity', to='ordered_item.ordereditem')),
            ],
        ),
    ]
